### ISSUE TITLE
time scales and formats

### ISSUE THREAD

**Issue by mwittig** [JsCommunity/human-format#6]
I am wondering how I can use time format ( or scale) effectively. Actually I want to output system uptime (seconds since boot) as (days) hh:mm, for example: 4 days, 22:32

I have tried the example included in the README which gives me the following:

```
var humanFormat = require("human-format");
var timeScale = new humanFormat.Scale({
    seconds: 0,
    minutes: 60,
    hours: 3600,
    days: 86400,
    months: 2592000,
})
console.log(humanFormat(425348, { scale: timeScale }));
```

which gives me 4.92 days

@julien-f @sweetpi How can I get the desired output format?

**Comment by sweetpi** [comment]
@mwittig I don't know. Did you update to the newest versiont? I don't remember this time scales as I've used the module.

**Comment by julien-f** [comment]
@mwittig Sorry for this very late response, it's not possible to have the format you want for now as it is not what this library has been designed for.

The initial intent was to be able to convert bytes to MB/GB/etc., the time scale you can see on the README is just another possible use but is indeed not the most common way to format durations.

You can either check [Moment.js](http://momentjs.com/) which is the reference for handling dates/times in JS or you can submit a PR to this library which suits your need while being also relevant for other scales.

For instance, an option to display `n` round units (`4 days, 22 hours and 22 minutes`) instead of a single floating one (`4.92 days`).

**Comment by Delagen** [comment]
I think you can try https://github.com/jsmreese/moment-duration-format

**Comment by julien-f** [comment]
@Delagen Thanks for your input :)

I'm going to close this issue, as it's old and not really something I want to implement.

**Comment by mwittig** [comment]
Thanks to all for the suggestions, to @Delagen in particular, as moment-duration-format is exactly what I need
